# Generated by Django 5.2.5 on 2025-08-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='status',
        ),
        migrations.AddField(
            model_name='debt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('creditor', 'Creditor'), ('debtor', 'Debtor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_debts', to=settings.AUTH_USER_MODEL),
        ),
    ]
