# Generated by Django 4.2.25 on 2025-10-10 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_debt_created_at_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-date_created'], 'verbose_name': 'Debt', 'verbose_name_plural': 'Debts'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='debt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='item',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='price',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount owed (for money) or estimated value (for product)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when debt was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Date when debt was last updated'),
        ),
        migrations.AddField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the debt', null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='product_name',
            field=models.CharField(blank=True, help_text='Name of product/item (if type is Product)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', help_text='Current status of the debt', max_length=20),
        ),
        migrations.AddField(
            model_name='debt',
            name='type',
            field=models.CharField(choices=[('money', 'Money'), ('product', 'Product')], default='money', help_text='Type of debt: Money or Product', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload payment proof/receipt (optional)', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction/Reference number (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Payment verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date when payment was verified', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('creditor', 'Creditor'), ('debtor', 'Debtor')], help_text='User role: Creditor or Debtor', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(help_text='Full name of the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Unique username.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='creditor',
            field=models.ForeignKey(help_text='User who is owed (creditor)', on_delete=django.db.models.deletion.CASCADE, related_name='creditor_debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(help_text='User who owes (debtor)', on_delete=django.db.models.deletion.CASCADE, related_name='debtor_debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when payment was recorded'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.ForeignKey(help_text='Associated debt for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.debt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('other', 'Other')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='Unique receipt number', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['creditor', 'status'], name='myapp_debt_credito_8bf196_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['debtor', 'status'], name='myapp_debt_debtor__39f446_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['debt', 'status'], name='myapp_payme_debt_id_59f1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', 'created_at'], name='myapp_payme_payer_i_7bb701_idx'),
        ),
    ]
