# Generated by Django 4.2.25 on 2025-10-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_email_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='Date when debt was marked as paid', null=True),
        ),
    ]
