# Generated by Django 4.2.25 on 2025-10-10 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_debt_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='paid_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Generated PDF receipt', null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', editable=False, help_text='Unique transaction ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('paypal', 'PayPal')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', help_text='Payment verification status', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_received', 'Payment Received'), ('debt_confirmed', 'Debt Confirmed'), ('debt_rejected', 'Debt Rejected'), ('debt_added', 'Debt Added')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('related_debt', models.ForeignKey(blank=True, help_text='Related debt (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.debt')),
                ('related_payment', models.ForeignKey(blank=True, help_text='Related payment (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.payment')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='myapp_notif_user_id_a5135a_idx')],
            },
        ),
    ]
