# Generated by Django 4.2.25 on 2025-10-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_debt_paid_date_payment_receipt_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_received', 'Payment Received'), ('debt_confirmed', 'Debt Confirmed'), ('debt_rejected', 'Debt Rejected'), ('debt_added', 'Debt Added'), ('debt_pending_confirmation', 'Debt Pending Confirmation')], help_text='Type of notification', max_length=50),
        ),
    ]
