# Generated by Django 4.2.25 on 2025-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_proof',
            field=models.FileField(blank=True, help_text='Proof of debt (photo, screenshot, or PDF) uploaded by debtor', null=True, upload_to='debt_proofs/'),
        ),
    ]
