# Generated by Django 4.2.25 on 2025-10-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_debt_debt_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='creditor_proof',
            field=models.FileField(blank=True, help_text='Proof that item/money was given to debtor (uploaded by creditor before confirming)', null=True, upload_to='creditor_proofs/'),
        ),
    ]
