# Generated by Django 4.2.25 on 2025-10-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_debt_creditor_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Date when debtor acknowledged receipt', null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor_acknowledged',
            field=models.BooleanField(default=False, help_text='Whether debtor has acknowledged receipt of item/money'),
        ),
        migrations.AddField(
            model_name='debt',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Proof of payment when creditor marks debt as paid (optional)', null=True, upload_to='payment_proofs_debt/'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='creditor_proof',
            field=models.FileField(blank=True, help_text='Proof of release - item/money was given to debtor (uploaded by creditor)', null=True, upload_to='creditor_proofs/'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('waiting_debtor_validation', 'Waiting for Debtor Validation'), ('active', 'Active'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending_confirmation', help_text='Current status of the debt', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_received', 'Payment Received'), ('debt_confirmed', 'Debt Confirmed'), ('debt_rejected', 'Debt Rejected'), ('debt_added', 'Debt Added'), ('debt_pending_confirmation', 'Debt Pending Confirmation'), ('proof_uploaded', 'Proof Uploaded'), ('debt_acknowledged', 'Debt Acknowledged'), ('debt_active', 'Debt Active')], help_text='Type of notification', max_length=50),
        ),
    ]
