# Generated by Django 4.2.25 on 2025-10-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_simplify_workflow_remove_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_summary',
            field=models.TextField(blank=True, help_text='Short bio or profile summary (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='[DEPRECATED] Date when debtor acknowledged receipt', null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtor_acknowledged',
            field=models.BooleanField(default=False, help_text='[DEPRECATED] Whether debtor has acknowledged receipt of item/money'),
        ),
    ]
