# Generated by Django 4.2.25 on 2025-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_customuser_profile_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date_paid',
            field=models.DateTimeField(blank=True, help_text='Date when debt was paid', null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid towards this debt', max_digits=10),
        ),
    ]
