# Generated by Django 4.2.25 on 2025-10-26 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_debt_date_paid_debt_paid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditorDebtorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, help_text='Total amount owed across all debts', max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=10)),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='Date of last payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this summary was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this summary was last updated')),
            ],
            options={
                'verbose_name': 'Creditor-Debtor Summary',
                'verbose_name_plural': 'Creditor-Debtor Summaries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='myapp_payme_payer_i_7bb701_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer',
        ),
        migrations.AddField(
            model_name='payment',
            name='creditor',
            field=models.ForeignKey(default=1, help_text='Creditor receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='debtor',
            field=models.ForeignKey(default=1, help_text='Debtor making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='made_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.ForeignKey(blank=True, help_text='Associated debt (for individual debt payments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.debt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('paypal', 'PayPal'), ('manual', 'Manual/Cash')], help_text='Payment method used', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['debtor', 'created_at'], name='myapp_payme_debtor__18f204_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['creditor', 'status'], name='myapp_payme_credito_57bb87_idx'),
        ),
        migrations.AddField(
            model_name='creditordebtorsummary',
            name='creditor',
            field=models.ForeignKey(help_text='Creditor in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='debtor_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditordebtorsummary',
            name='debtor',
            field=models.ForeignKey(help_text='Debtor in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='creditor_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='summary',
            field=models.ForeignKey(blank=True, help_text='Associated creditor-debtor summary', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.creditordebtorsummary'),
        ),
        migrations.AlterUniqueTogether(
            name='creditordebtorsummary',
            unique_together={('creditor', 'debtor')},
        ),
    ]
