# Generated by Django 4.2.25 on 2025-10-26 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_creditordebtorsummary_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditordebtorsummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creditordebtorsummary',
            name='creditor',
        ),
        migrations.RemoveField(
            model_name='creditordebtorsummary',
            name='debtor',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='myapp_payme_debtor__18f204_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='myapp_payme_credito_57bb87_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='creditor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='summary',
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(default=1, help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.ForeignKey(default=1, help_text='Associated debt for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.debt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('paypal', 'PayPal')], help_text='Payment method used', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', 'created_at'], name='myapp_payme_payer_i_7bb701_idx'),
        ),
        migrations.DeleteModel(
            name='CreditorDebtorSummary',
        ),
    ]
