# Generated by Django 4.2.25 on 2025-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_creditordebtorsummary_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='proof',
        ),
        migrations.AddField(
            model_name='payment',
            name='creditor_proof',
            field=models.FileField(blank=True, help_text="Creditor's proof of receipt (for cash payments)", null=True, upload_to='payment_proofs/creditor/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='debtor_proof',
            field=models.FileField(blank=True, help_text="Debtor's proof of payment (for cash payments)", null=True, upload_to='payment_proofs/debtor/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash')], help_text='Payment method used', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending_debtor_proof', 'Awaiting Debtor Proof'), ('pending_creditor_proof', 'Awaiting Creditor Proof'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', help_text='Payment verification status', max_length=30),
        ),
    ]
