# Generated by Django 4.2.25 on 2025-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_payment_proof_payment_creditor_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, help_text='Related object ID (for generic references)', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_received', 'Payment Received'), ('payment_pending', 'Payment Pending'), ('payment_debtor_proof_uploaded', 'Debtor Proof Uploaded'), ('payment_creditor_proof_uploaded', 'Creditor Proof Uploaded'), ('payment_completed', 'Payment Completed'), ('partial_payment_received', 'Partial Payment Received'), ('debt_confirmed', 'Debt Confirmed'), ('debt_rejected', 'Debt Rejected'), ('debt_added', 'Debt Added'), ('debt_pending_confirmation', 'Debt Pending Confirmation'), ('proof_uploaded', 'Proof Uploaded'), ('debt_acknowledged', 'Debt Acknowledged'), ('debt_active', 'Debt Active')], help_text='Type of notification', max_length=50),
        ),
    ]
