# Generated by Django 5.2.7 on 2025-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_notification_title_notification_related_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='hidden_from_debtor',
            field=models.BooleanField(default=False, help_text="If True, debt is hidden from debtor's view (soft delete)"),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('active', 'Active'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending_confirmation', help_text='Current status of the debt', max_length=30),
        ),
    ]
