# Generated by Django 5.2.7 on 2025-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_debt_hidden_from_debtor_alter_debt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_system_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can access the custom admin dashboard.'),
        ),
    ]
