# Generated by Django 5.2.7 on 2025-11-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_customuser_is_system_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_system_admin',
        ),
    ]
