# Generated by Django 5.2.7 on 2025-11-15 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_customuser_is_system_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Admin Login'), ('view_users', 'View Users List'), ('view_user_detail', 'View User Detail'), ('view_debts', 'View Debts List'), ('view_debt_detail', 'View Debt Detail'), ('view_payments', 'View Payments List'), ('approve_payment', 'Approve Payment'), ('reject_payment', 'Reject Payment'), ('view_activity', 'View Activity Log')], help_text='Type of action performed', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('related_id', models.IntegerField(blank=True, help_text='Related object ID (if applicable)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('user', models.ForeignKey(help_text='Admin user who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='myapp_admin_user_id_5454bd_idx'), models.Index(fields=['action', '-timestamp'], name='myapp_admin_action_4b8980_idx')],
            },
        ),
    ]
