# Generated by Django 5.2.7 on 2025-11-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_adminactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('creditor', 'Creditor'), ('debtor', 'Debtor'), ('admin', 'Admin')], help_text='User role: Creditor, Debtor, or Admin', max_length=20),
        ),
    ]
