# Generated by Django 5.2.7 on 2025-11-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Admin Login'), ('view_users', 'View Users List'), ('view_user_detail', 'View User Detail'), ('view_debts', 'View Debts List'), ('view_debt_detail', 'View Debt Detail'), ('view_payments', 'View Payments List'), ('approve_payment', 'Approve Payment'), ('reject_payment', 'Reject Payment'), ('view_activity', 'View Activity Log'), ('update_settings', 'Update Settings')], help_text='Type of action performed', max_length=50),
        ),
    ]
