# Generated by Django 5.2.7 on 2025-11-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_adminactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='hidden_from_creditor',
            field=models.BooleanField(default=False, help_text="If True, debt is hidden from creditor's view (soft delete)"),
        ),
    ]
