# Generated by Django 5.2.7 on 2025-11-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_debt_hidden_from_creditor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='hidden_from_creditor',
        ),
    ]
