# Generated by Django 5.2.7 on 2025-11-25 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_debt_hidden_from_creditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the payment (auto-filled when debt is deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.ForeignKey(blank=True, help_text='Associated debt for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='myapp.debt'),
        ),
    ]
