# Generated by Django 5.2.7 on 2025-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_payment_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the payment (auto-filled when debt is deleted)', null=True),
        ),
    ]
