# Generated by Django 5.2.7 on 2025-11-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_add_back_payment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
    ]
