# Generated by Django 5.2.7 on 2025-11-26 00:19

from django.db import migrations, connection


def remove_hidden_from_creditor_field(apps, schema_editor):
    """
    Remove hidden_from_creditor field from myapp_debt table if it exists.
    This handles the case where the field exists in production but not in development.
    """
    with connection.cursor() as cursor:
        # Check if the column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM pragma_table_info('myapp_debt') 
            WHERE name = 'hidden_from_creditor'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if column_exists:
            # For SQLite, we need to recreate the table without the column
            cursor.execute("""
                CREATE TABLE myapp_debt_new (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    type VARCHAR(20) NOT NULL,
                    amount DECIMAL(10, 2) NOT NULL,
                    product_name VARCHAR(255) NULL,
                    description TEXT NULL,
                    debt_proof VARCHAR(100) NULL,
                    creditor_proof VARCHAR(100) NULL,
                    payment_proof VARCHAR(100) NULL,
                    debtor_acknowledged BOOL NOT NULL,
                    acknowledged_at DATETIME NULL,
                    paid_amount DECIMAL(10, 2) NOT NULL,
                    status VARCHAR(30) NOT NULL,
                    hidden_from_debtor BOOL NOT NULL,
                    date_created DATETIME NOT NULL,
                    date_updated DATETIME NOT NULL,
                    date_paid DATETIME NULL,
                    creditor_id INTEGER NOT NULL REFERENCES auth_customuser(id),
                    debtor_id INTEGER NOT NULL REFERENCES auth_customuser(id)
                )
            """)
            
            cursor.execute("""
                INSERT INTO myapp_debt_new (
                    id, type, amount, product_name, description, debt_proof, 
                    creditor_proof, payment_proof, debtor_acknowledged, acknowledged_at,
                    paid_amount, status, hidden_from_debtor, date_created, 
                    date_updated, date_paid, creditor_id, debtor_id
                )
                SELECT 
                    id, type, amount, product_name, description, debt_proof, 
                    creditor_proof, payment_proof, debtor_acknowledged, acknowledged_at,
                    paid_amount, status, hidden_from_debtor, date_created, 
                    date_updated, date_paid, creditor_id, debtor_id
                FROM myapp_debt
            """)
            
            cursor.execute("DROP TABLE myapp_debt")
            cursor.execute("ALTER TABLE myapp_debt_new RENAME TO myapp_debt")
            
            # Recreate indexes
            cursor.execute("CREATE INDEX 'myapp_debt_creditor_id_status_idx' ON 'myapp_debt' ('creditor_id', 'status')")
            cursor.execute("CREATE INDEX 'myapp_debt_debtor_id_status_idx' ON 'myapp_debt' ('debtor_id', 'status')")


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_description_field_fix'),
    ]

    operations = [
        migrations.RunPython(remove_hidden_from_creditor_field, reverse_code=migrations.RunPython.noop),
    ]
