# Generated by Django 5.2.7 on 2026-01-09 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_add_hidden_from_creditor_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='hidden_from_creditor',
            field=models.BooleanField(default=False, help_text="If True, debt is hidden from creditor's view (soft delete)"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='debt',
            field=models.ForeignKey(help_text='Associated debt for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.debt'),
        ),
    ]
